baseurl: /llmmodels
title: Deep Generative Models
subtitle: Lecture notes
author: Mounika Jampana
simple_search: http://google.com/search
description: Leture of Paper.
name: notes
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
# timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
destination: docs
google_analytics: UA-129020129-1
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
theme: jekyll-theme-minimal
